#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/noop
#
# IDENTIFICATION
#    src/backend/access/noop/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/noop
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = noop.o

include $(top_srcdir)/src/backend/common.mk
